### ISSUE TITLE
Fundmylaptop CD (backend) 

### ISSUE THREAD

**Issue by Babsmutini** [hngi/Fund-My-Laptop-BE#108]
Fund my laptop Continuous Delivery/Deployment
@anubabajide @brpo01

**Comment by anubabajide** [comment]
![image](https://user-images.githubusercontent.com/46856621/86309704-461e9a80-bc14-11ea-8a0b-92ab76d4bf1d.png)
![image](https://user-images.githubusercontent.com/46856621/86309722-53d42000-bc14-11ea-8373-a35f1b0835e2.png)
