### ISSUE TITLE
Consume FAQ.blade.php

### ISSUE THREAD

**Issue by frankremmy** [hngi/Fund-My-Laptop-BE#155]

**Comment by horlathunbhosun** [comment]
There is no endpoint for FaQ to consume @frankremmy

**Comment by horlathunbhosun** [comment]
what should i do @frankremmy

**Comment by frankremmy** [comment]
@horlathunbhosun It's here https://github.com/hngi/Fund-My-Laptop-BE/blob/staging/routes/api.php

**Comment by horlathunbhosun** [comment]
There is no Faq endpoint i check through it I couldn't find any

**Comment by horlathunbhosun** [comment]
@frankremmy

**Comment by frankremmy** [comment]
Oh sorry. We may not need to consume it since it has no endpoint. Sorry about that.

**Comment by horlathunbhosun** [comment]
Can you assign 22 @frankremmy  since this is closed??
