### ISSUE TITLE
SignUp 

### ISSUE THREAD

**Issue by tobbhie** [hngi/Fund-My-Laptop-BE#197]
Register User and redirect to login

**Comment by ajadi473** [comment]
i was on this and already completed thi task..............

**Comment by ajadi473** [comment]
"Implement Profile Setup & sign up
users can 

- sign up, after signing up they
- receive a confirmation mail with a link to the profile setup.
- verify mail
- redirect to Blade template for email verify,profilesetup1 & 2 not currently available
