### ISSUE TITLE
Login (Return Token) + Logout

### ISSUE THREAD

**Issue by frankremmy** [hngi/Fund-My-Laptop-BE#2]
- Accept Email and Password

- Return Token and User profile upon success Login

- Make sure only verified email account can Login

**Comment by tobbhie** [comment]
On it

**Comment by mike-ske** [comment]
I am working on logout

**Comment by mike-ske** [comment]
What am I to do

**Comment by mike-ske** [comment]
I was assigned by @Eromosele I am supposed to work on logout

**Comment by mike-ske** [comment]
#2 login (Return Token) + Logout
