### ISSUE TITLE
Admin Block a user account

### ISSUE THREAD

**Issue by frankremmy** [hngi/Fund-My-Laptop-BE#23]
* Enable Admin To Block account

**Comment by dreywandowski** [comment]
Can I have this task assigned to me please?

**Comment by dreywandowski** [comment]
@frankremmy  I just made a PR. Did you re-assign this issue to someone else?

**Comment by frankremmy** [comment]
@dreywandowski sorry. I thought you're no longer interested in the task again.

**Comment by dreywandowski** [comment]
Completed
