### ISSUE TITLE
Admin View all uncompleted requests with their count

### ISSUE THREAD

**Issue by frankremmy** [hngi/Fund-My-Laptop-BE#27]
"* Allow admin view all uncompleted Requests 
return count as well"

**Comment by Ojsholly** [comment]
In progress

**Comment by Ojsholly** [comment]
By uncompleted, isActive = 0, isSuspended = 0 and isActive = 1? Is that the logic? If not, kindly state the required logic. 
P.S Comments would have been helpful.
